### PR TITLE
Cloudflare API Token Authentication Support

### PR DESCRIPTION
**Pull request by nikduvall**
Updated Plugin as follows:

1.  Added support for Cloudflare API Token Authentication.  This is the more secure method of authenticating since it allows you to set authorization controls versus using a global API Key that has full account access.  This change is designed to be backwards compatible with using API Key Authentication so that it does not break any existing deployments on Netlify.

2.  Moved Environment verification checks to **_onEnd_** since calling **_utils.build.failBuild_** within **_onPreBuild_** does not prevent **_onEnd_** from firing.

### CODE REVIEW

**Comment by chrism2671** [comment]
Thank you for the PR; this looks fine- merging!

**Comment by chrism2671** [comment]
I've published v1.1.0 to npm.

Can I ask you to please open a pull request on Netlify's plugin directory here:

https://github.com/netlify/plugins/edit/master/plugins.json - checking it meets the requirements. It would be a great help.

**Comment by nikduvall** [comment]
Hi @chrism2671,

I would be happy to do so.

Regards,
@nikduvall

**Comment by nikduvall** [comment]
[PR-119](https://github.com/netlify/plugins/pull/119) created to update the Netlify plugin.json file.

**Pull request merged**
